version: '3.1'

services:
  php_api:
    build: ./api_php
    container_name: api_c
    ports:
      - '80:80'
    env_file:
      - ./api_php/.env
    volumes:
      - ./api_php:/var/www/html
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:8
    container_name: mysql_c
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
